### ISSUE TITLE
About authorship

### ISSUE THREAD

**Issue by niuniomartinez** [Shoozza/allegro-pas5#2]
Hi,

I've read this project description "Fork **and new home** of the allegro-pas 5.0 branch", and in the AUTHORS file you wrote that I'm "creator **and former maintainer** of this wrapper."   That's not true.  I'm still working on it on SourceForge (last commit on January 2017 ATM).

Of course you can modify and use Allegro.pas in any way you want but please fix those and any other mention about you're the current maintainer.  Also add notes on the documentation stating that the Allegro.pas project is hosted at SourceForge.

Anyway, I'll create a second repository here at GitHub with a copy Allegro.pas that I'll try to keep synchronized with the official SoruceForge one.  You're free to fork it to keep your fork up-to-date

Thank you.

**Comment by Shoozza** [comment]
Hello, I updated the project description, README and AUTHORS file to avoid confusion.

**Comment by niuniomartinez** [comment]
Thanks. :+1:
